/**
 * Generated by scripts/stamp-build.mjs at build time. Do not edit.
 *
 * Committed rather than git-ignored so that a checkout builds without a
 * preparation step, and so a deployed build can be traced to a commit.
 */

export const APP_VERSION = '1.0.0'
export const APP_BUILD = '36ab9cb69'
export const BUILT_AT = '2026-09-12T19:24:20.000Z'
