/**
 * Stamps this build with an identity, so every copy of the application can
 * tell whether it is the current one.
 *
 * Three places need the same answer and must never disagree:
 *
 *   - the application itself, to show "you are running build X" and to ask
 *     the server whether something newer exists;
 *   - /api/version, which is what the server answers with;
 *   - the service worker, whose file contents must CHANGE between deploys or
 *     the browser will never notice there is an update. That is the whole
 *     mechanism by which an installed PWA refreshes itself, and a service
 *     worker with a fixed cache name silently serves last month's code for
 *     ever. It did, until this script existed.
 *
 * Run before the build (to generate the sources) and again after it (to
 * stamp the built service worker, which vite copies verbatim from public/).
 */
import { execSync } from 'node:child_process'
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const pkg = JSON.parse(readFileSync(resolve(root, 'package.json'), 'utf8'))

function git(command, fallback) {
  try {
    return execSync(command, { cwd: root, stdio: ['ignore', 'pipe', 'ignore'] }).toString().trim()
  } catch {
    return fallback
  }
}

/**
 * The identity of the commit being built.
 *
 * Vercel builds in a checkout with no .git directory but sets these, so a
 * deployment can still say which commit it is.
 */
function commit() {
  const sha = process.env.VERCEL_GIT_COMMIT_SHA ?? git('git rev-parse HEAD', '')
  const iso = process.env.VERCEL_GIT_COMMIT_SHA
    ? null
    : git('git log -1 --format=%cI', null)
  return { sha: sha ? sha.slice(0, 9) : 'nogit', iso }
}

/**
 * A build identity that is the same for every build of the same commit.
 *
 * This has to be derived from the commit and not from the clock. The phone,
 * the desktop application and the deployment are each built separately - by
 * `npm run apk`, by electron-builder and by Vercel - and every one of them
 * compares its own identity against the server's to decide whether it is out
 * of date. A timestamp would differ between those three builds of identical
 * code, and every installed copy would announce an update that does not
 * exist, for ever.
 */
export function buildInfo() {
  const { sha, iso } = commit()
  return {
    version: pkg.version,
    // The commit alone, with no clock in it. Two builds of the same source
    // must produce the same answer or every device compares itself against a
    // deployment it cannot ever match.
    build: sha,
    builtAt: (iso ? new Date(iso) : new Date()).toISOString(),
    known: sha !== 'nogit',
  }
}

const HEADER = `/**
 * Generated by scripts/stamp-build.mjs at build time. Do not edit.
 *
 * Committed rather than git-ignored so that a checkout builds without a
 * preparation step, and so a deployed build can be traced to a commit.
 */
`

function writeIfChanged(path, contents) {
  if (existsSync(path) && readFileSync(path, 'utf8') === contents) return false
  mkdirSync(dirname(path), { recursive: true })
  writeFileSync(path, contents)
  return true
}

/** Generates the TypeScript the application and the API both import. */
export function writeSources(info) {
  // A build environment with no git and no commit variables - a deployment
  // built from an upload rather than a checkout - cannot work out which
  // commit it is. The generated files are committed precisely so that this
  // case keeps the right answer instead of overwriting it with 'nogit'.
  if (!info.known && existsSync(resolve(root, 'src/core/buildInfo.ts'))) return []

  const body = `${HEADER}
export const APP_VERSION = '${info.version}'
export const APP_BUILD = '${info.build}'
export const BUILT_AT = '${info.builtAt}'
`
  const written = []
  if (writeIfChanged(resolve(root, 'src/core/buildInfo.ts'), body)) written.push('src/core/buildInfo.ts')
  if (writeIfChanged(resolve(root, 'api/_shared/buildInfo.ts'), body)) written.push('api/_shared/buildInfo.ts')
  return written
}

/**
 * Stamps the built service worker.
 *
 * Without this the file is byte-identical between deployments, the browser
 * concludes there is nothing new, and an installed PWA never updates.
 */
export function stampServiceWorker(info) {
  const path = resolve(root, 'dist/sw.js')
  if (!existsSync(path)) return false
  const source = readFileSync(path, 'utf8')
  // No marker means the worker was built from something other than the
  // current public/sw.js. Reporting success would let a release ship a
  // service worker that is identical between deployments - the exact
  // condition in which installed copies never update again.
  if (!source.includes('__BUILD__')) return false
  const stamped = source.replaceAll('__BUILD__', info.build)
  writeFileSync(path, stamped)
  return true
}

/**
 * Reads back what the pre-build step generated.
 *
 * The post step must not recompute the identity: a build that crosses a
 * minute boundary would stamp the service worker with a different id from
 * the one inside the application, and the two would disagree for ever about
 * whether an update exists.
 */
function generatedInfo() {
  const path = resolve(root, 'src/core/buildInfo.ts')
  if (!existsSync(path)) return null
  const source = readFileSync(path, 'utf8')
  const build = source.match(/APP_BUILD = '([^']+)'/)?.[1]
  const version = source.match(/APP_VERSION = '([^']+)'/)?.[1]
  const builtAt = source.match(/BUILT_AT = '([^']+)'/)?.[1]
  return build ? { build, version, builtAt } : null
}

const mode = process.argv[2] ?? 'pre'

if (mode === 'post') {
  const info = generatedInfo()
  if (!info) {
    console.log('  service worker not stamped (no generated build info)')
    process.exit(0)
  }
  const done = stampServiceWorker(info)
  console.log(
    done
      ? `  service worker stamped ${info.build}`
      : '  service worker not stamped (dist/sw.js missing or has no marker)',
  )
} else {
  const info = buildInfo()
  const written = writeSources(info)
  const effective = generatedInfo()?.build ?? info.build
  console.log(`  build ${effective}${info.known ? '' : ' (kept: this environment has no commit information)'}`)
  for (const f of written) console.log(`  wrote ${f}`)
}
